networks:
  web:
    name: web
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    container_name: rp_nginx
    restart: unless-stopped
    ports:
      - "4000:4000"         # publik LAN kamu
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - web
