services:
  app:
    build: .
    image: hello_phoenix-app
    container_name: elixir_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MIX_ENV=prod
      - PHX_SERVER=true
      - PORT=4000
    ports:
      - "4000:4000"
