# docker-compose.yml  (hapus baris `version:` biar gak ada warning)
services:
  postgres:
    image: postgres:15
    container_name: elixir_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hello_phoenix_prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hello_phoenix_prod -h 127.0.0.1 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s

  app_blue:
    build: .
    container_name: elixir_app_blue
    restart: unless-stopped
    environment:
      MIX_ENV: prod
      PHX_SERVER: "true"
      PHX_HOST: "10.10.10.11"
      PHX_PORT: "4000"                # ← konsisten
      PORT: "4000"                    # ← untuk lib tertentu yang baca PORT
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/hello_phoenix_prod"
      SECRET_KEY_BASE: "GANTI_DENGAN_HASIL_mix phx.gen.secret"
      ELIXIR_ERL_OPTIONS: "+fnu"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "4001:4000"
    # Healthcheck pakai wget agar tak perlu curl
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${PHX_PORT:-4000}/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 30
      start_period: 30s

  app_green:
    build: .
    container_name: elixir_app_green
    restart: unless-stopped
    environment:
      MIX_ENV: prod
      PHX_SERVER: "true"
      PHX_HOST: "10.10.10.11"
      PHX_PORT: "4000"
      PORT: "4000"
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/hello_phoenix_prod"
      SECRET_KEY_BASE: "GANTI_DENGAN_HASIL_mix phx.gen.secret"
      ELIXIR_ERL_OPTIONS: "+fnu"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "4002:4000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${PHX_PORT:-4000}/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 30
      start_period: 30s

  lb:
    image: nginx:alpine
    container_name: elixir_lb
    restart: unless-stopped
    ports:
      - "4000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/upstream_target.conf:/etc/nginx/conf.d/upstream_target.conf:ro
    depends_on:
      app_blue:
        condition: service_started
      app_green:
        condition: service_started

volumes:
  pgdata:
