services:
  app_blue:
    build: .
    container_name: elixir_app_blue
    env_file: .env
    environment:
      - MIX_ENV=prod
      - PHX_SERVER=true
      - PORT=4000
    ports:
      - "4001:4000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:4000/ || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 20

  app_green:
    build: .
    container_name: elixir_app_green
    env_file: .env
    environment:
      - MIX_ENV=prod
      - PHX_SERVER=true
      - PORT=4000
    ports:
      - "4002:4000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:4000/ || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 20

  lb:
    image: nginx:1.25-alpine
    container_name: elixir_lb
    ports:
      - "4000:4000"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ./nginx/includes/upstream_target.inc:/etc/nginx/includes/upstream_target.inc:rw
    restart: unless-stopped


